### ISSUE TITLE
Calculating the posterior prediction of sparse.sglmm

### ISSUE THREAD

**Issue by JeremyGelb** [donaldmusgrove/ngspatial#1]
Hi,
I am fitting a gaussian model using the RSR method of the sparse.sglmm function. Everything works well, but I would like to calculate the posterior prediction of the model and not only the point estimates available in fit$linear.predictors.

So I tried to build a function (see the next block of code) using the posteriors of beta and gamma to build the posterior of the linear predictor.
NB : I am only using attractive Moran eigenvectors.

```R
Sample_ypred <- function(fit,NDraws=10){
  #extract the original data from the model (fixed and random effects)
  X <- fit$X
  M <- fit$M
  Samples <- list()
  #iterate for the number of draws required
  for (i in 1:NDraws){
    #sample the parameters from the posterior distributions of the fitted model
    CoeffFix <- apply(fit$beta.sample,2,function(x){return(sample(x,size=nrow(X)))})
    CoefRandom <- apply(fit$gamma.sample,2,function(x){return(sample(x,size=nrow(X)))})               
    #Add all the values to get a prediction
    FixedPred <- CoeffFix*X
    RandomPred <- CoefRandom*M
    #so, here we have the linear predictor...
    Pred <- rowSums(FixedPred)+rowSums(RandomPred)
    #Store it in a list
    Samples[[length(Samples)+1]]<-Pred
  }
  #Return the NDraws
  Preds <- do.call(cbind,Samples)
  return(Preds)
} 
```

In the best case, I would like to build the posterior of the prediction including the posterior variance of the gaussian model. I think that I should add something at the end of the previous function : 

```R
Pred <- rowSums(FixedPred)+rowSums(RandomPred)
VarPred <- rnorm(length(Pred),Pred,VariancePosterior)
```
If this is correct, I need the posterior of the variance of the gaussian model, but I can't find it in the outputs of the fit object.

Is the approach correct ? If so, how could I get that vector containing the posterior of the variance ?

NB : if the function above is right, it could be usefull to calculate bayes_r2 as proposed with [stan models](https://github.com/jgabry/bayes_R2/blob/master/bayes_R2.R).

Thank you for your help and your time !

**Comment by donaldmusgrove** [comment]
Hi, 
The code here is not active and has not been touched in 3+ years. If you're only using `sparse.sglmm` and not the multivariate functionality, I suggest that you use the original [ngspatial](https://github.com/cran/ngspatial) package. The ngspatial package has been updated within the last 18 months and should do what you want.

**Comment by JeremyGelb** [comment]
Thank you for your answer, I took some time to read all the doc and the R functions, but I am still not able to find if the sparse.glmm function give in the ouputs the posterior draws of **sigma**. In the case a gaussian model is used : y ~ normal(mu,**sigma**), with mu = X*B + M*GAMMA (only attractive spatial eigen vectors). I am missing something ?

**Comment by donaldmusgrove** [comment]
I looked at the code and the model uses the inverse of the variance and not standard deviation. To get the correct inverse of the variance, use the `tau.h.sample` output. This is all in the help page by the way.
